---

- name: Check EPEL repository
  shell: yum repolist | grep -qi EPEL
  register: _yum_epel__repository_status
  check_mode: no
  changed_when: False
  failed_when: _yum_epel__repository_status.rc == 2
  args:
    warn: False
  when: ansible_os_family == 'RedHat' and ansible_pkg_mgr == 'yum'

- name: Add EPEL repository
  yum:
    name:  epel-release
    state: present
  when: ansible_os_family == 'RedHat' and ansible_pkg_mgr == 'yum' and _yum_epel__repository_status.rc != 0

- name: Remove EPEL repository
  yum:
    name:  epel-release
    state: absent
  when: ansible_os_family == 'RedHat' and ansible_pkg_mgr == 'yum' and _yum_epel__repository_status.rc == 0
  notify: ['epel-clean-yum-metadata']
